"""initial persistence schema

Revision ID: 5a9ee65c1497
Revises:
Create Date: 2026-08-27 12:48:51.150927
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5a9ee65c1497"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "planning_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("horizon_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bucket_duration", sa.Interval(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("input_data_version", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bucket_duration > interval '0 seconds'", name="ck_planning_runs_bucket_duration"
        ),
        sa.CheckConstraint("horizon_end > horizon_start", name="ck_planning_runs_horizon"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_runs_organization_id"), "planning_runs", ["organization_id"], unique=False
    )
    op.create_table(
        "skus",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("base_unit_scale", sa.BigInteger(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("base_unit_scale > 0", name="ck_skus_base_unit_scale_positive"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_skus_org_code"),
    )
    op.create_index(op.f("ix_skus_organization_id"), "skus", ["organization_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("canonical_source_id", sa.String(length=255), nullable=False),
        sa.Column("canonical_source_type", sa.String(length=64), nullable=False),
        sa.Column("upstream_dataset", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "canonical_source_id", name="uq_sources_canonical"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_suppliers_org_code"),
    )
    op.create_index(
        op.f("ix_suppliers_organization_id"), "suppliers", ["organization_id"], unique=False
    )
    op.create_table(
        "warehouses",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_warehouses_org_code"),
    )
    op.create_index(
        op.f("ix_warehouses_organization_id"), "warehouses", ["organization_id"], unique=False
    )
    op.create_table(
        "candidate_plans",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column("feasibility", sa.String(length=32), nullable=False),
        sa.Column("shortage_base_units", sa.BigInteger(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("solver_version", sa.String(length=128), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("planning_run_id", "stable_key", name="uq_candidate_plans_stable"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.String(length=64), nullable=True),
        sa.Column("warehouse_id", sa.String(length=64), nullable=True),
        sa.Column("supplier_id", sa.String(length=64), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("predicate", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("valid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("human_summary", sa.Text(), nullable=False),
        sa.Column("materiality", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(valid_at IS NOT NULL AND valid_from IS NULL AND valid_until IS NULL) OR "
            "(valid_at IS NULL AND valid_from IS NOT NULL AND valid_until > valid_from)",
            name="ck_claims_validity",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"]),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"]),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_lots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.String(length=64), nullable=False),
        sa.Column("warehouse_id", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("manufactured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expiry_kind", sa.String(length=16), nullable=False),
        sa.Column("initial_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expiry_kind IN ('use_by', 'best_before')", name="ck_inventory_lots_expiry_kind"
        ),
        sa.CheckConstraint(
            "status IN ('available', 'reserved', 'quarantined', 'expired', 'depleted')",
            name="ck_inventory_lots_status",
        ),
        sa.CheckConstraint("expires_at > received_at", name="ck_inventory_lots_expiry"),
        sa.CheckConstraint("initial_quantity > 0", name="ck_inventory_lots_initial_quantity"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_lots_fefo",
        "inventory_lots",
        ["warehouse_id", "sku_id", "expires_at", "id"],
        unique=False,
    )
    op.create_table(
        "inventory_reservations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.String(length=64), nullable=False),
        sa.Column("warehouse_id", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("business_reference", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_inventory_reservations_quantity"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_inventory_reservations_idempotency"
        ),
    )
    op.create_table(
        "lineage_edges",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("from_type", sa.String(length=32), nullable=False),
        sa.Column("from_id", sa.String(length=64), nullable=False),
        sa.Column("relationship", sa.String(length=32), nullable=False),
        sa.Column("to_type", sa.String(length=32), nullable=False),
        sa.Column("to_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "planning_run_id",
            "from_type",
            "from_id",
            "relationship",
            "to_type",
            "to_id",
            name="uq_lineage_edges",
        ),
    )
    op.create_table(
        "mcp_calls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("server", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("normalized_arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "planning_buckets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name="ck_planning_buckets_bounds"),
        sa.CheckConstraint("sequence >= 0", name="ck_planning_buckets_sequence"),
        sa.ForeignKeyConstraint(["planning_run_id"], ["planning_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("planning_run_id", "sequence", name="uq_planning_buckets_sequence"),
        sa.UniqueConstraint("planning_run_id", "starts_at", name="uq_planning_buckets_start"),
    )
    op.create_index(
        op.f("ix_planning_buckets_planning_run_id"),
        "planning_buckets",
        ["planning_run_id"],
        unique=False,
    )
    op.create_table(
        "supplier_offers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.String(length=64), nullable=False),
        sa.Column("destination_warehouse_id", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("lead_time", sa.Interval(), nullable=False),
        sa.Column("minimum_order_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("pack_size", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("expected_shelf_life", sa.Interval(), nullable=True),
        sa.Column("source_version", sa.String(length=128), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("available_quantity >= 0", name="ck_supplier_offers_available"),
        sa.CheckConstraint("minimum_order_quantity >= 0", name="ck_supplier_offers_moq"),
        sa.CheckConstraint("pack_size > 0", name="ck_supplier_offers_pack_size"),
        sa.CheckConstraint("unit_price >= 0", name="ck_supplier_offers_price"),
        sa.CheckConstraint("valid_until > valid_from", name="ck_supplier_offers_validity"),
        sa.ForeignKeyConstraint(
            ["destination_warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "planning_run_id",
            "supplier_id",
            "sku_id",
            "destination_warehouse_id",
            "source_version",
            name="uq_supplier_offers_version",
        ),
    )
    op.create_table(
        "workflow_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("causation_id", sa.String(length=128), nullable=True),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("planning_run_id", "sequence", name="uq_workflow_events_sequence"),
    )
    op.create_table(
        "demand_forecasts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("bucket_id", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.String(length=64), nullable=False),
        sa.Column("warehouse_id", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("source_version", sa.String(length=128), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("priority > 0", name="ck_demand_forecasts_priority"),
        sa.CheckConstraint("quantity >= 0", name="ck_demand_forecasts_quantity"),
        sa.ForeignKeyConstraint(
            ["bucket_id"],
            ["planning_buckets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "planning_run_id",
            "bucket_id",
            "sku_id",
            "warehouse_id",
            "source_version",
            name="uq_demand_forecasts_version",
        ),
    )
    op.create_table(
        "distribution_lines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.String(length=64), nullable=False),
        sa.Column("source_warehouse_id", sa.String(length=64), nullable=False),
        sa.Column("destination_warehouse_id", sa.String(length=64), nullable=False),
        sa.Column("departure_bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("source_lot_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_distribution_lines_quantity"),
        sa.ForeignKeyConstraint(
            ["destination_warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["candidate_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("mcp_call_id", sa.String(length=64), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=True),
        sa.Column("content_summary", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_version", sa.String(length=128), nullable=False),
        sa.Column("raw_response_sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("origin IN ('external', 'agent_derived')", name="ck_evidence_origin"),
        sa.ForeignKeyConstraint(
            ["mcp_call_id"],
            ["mcp_calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id", "raw_response_sha256", "observation_version", name="uq_evidence_identity"
        ),
    )
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("lot_id", sa.String(length=64), nullable=False),
        sa.Column("movement_type", sa.String(length=16), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("reserved_delta", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("business_reference", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "movement_type IN ('receipt', 'reservation', 'release', 'shipment', "
            "'transfer', 'waste', 'adjustment')",
            name="ck_inventory_movements_type",
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0 OR reserved_delta <> 0", name="ck_inventory_movements_nonzero"
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["inventory_lots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "idempotency_key",
            "lot_id",
            name="uq_inventory_movements_idempotency",
        ),
    )
    op.create_index(
        "ix_inventory_movements_lot_occurred",
        "inventory_movements",
        ["lot_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_table(
        "jury_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("implementation_version", sa.String(length=64), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("component_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("integrity_score", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("gate_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("final_state", sa.String(length=32), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "per_claim_contributions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["candidate_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "planning_run_id", "plan_id", "policy_version", name="uq_jury_decisions_version"
        ),
    )
    op.create_table(
        "procurement_lines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.String(length=64), nullable=False),
        sa.Column("destination_warehouse_id", sa.String(length=64), nullable=False),
        sa.Column("arrival_bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("landed_cost", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.CheckConstraint("quantity > 0 AND landed_cost >= 0", name="ck_procurement_lines_values"),
        sa.ForeignKeyConstraint(
            ["destination_warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["candidate_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_claims",
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.Column("claim_id", sa.String(length=64), nullable=False),
        sa.Column("relationship", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evidence_id", "claim_id"),
    )
    op.create_table(
        "execution_audits",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("planning_run_id", sa.String(length=64), nullable=False),
        sa.Column("approved_plan_id", sa.String(length=64), nullable=False),
        sa.Column("jury_decision_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("approval_policy_version", sa.String(length=64), nullable=False),
        sa.Column("action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("compensation_status", sa.String(length=32), nullable=True),
        sa.Column("external_references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_plan_id"],
            ["candidate_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["jury_decision_id"],
            ["jury_decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planning_run_id"],
            ["planning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_execution_audits_idempotency"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("execution_audits")
    op.drop_table("evidence_claims")
    op.drop_table("procurement_lines")
    op.drop_table("jury_decisions")
    op.drop_index("ix_inventory_movements_lot_occurred", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_table("evidence")
    op.drop_table("distribution_lines")
    op.drop_table("demand_forecasts")
    op.drop_table("workflow_events")
    op.drop_table("supplier_offers")
    op.drop_index(op.f("ix_planning_buckets_planning_run_id"), table_name="planning_buckets")
    op.drop_table("planning_buckets")
    op.drop_table("mcp_calls")
    op.drop_table("lineage_edges")
    op.drop_table("inventory_reservations")
    op.drop_index("ix_inventory_lots_fefo", table_name="inventory_lots")
    op.drop_table("inventory_lots")
    op.drop_table("claims")
    op.drop_table("candidate_plans")
    op.drop_index(op.f("ix_warehouses_organization_id"), table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index(op.f("ix_suppliers_organization_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_table("sources")
    op.drop_index(op.f("ix_skus_organization_id"), table_name="skus")
    op.drop_table("skus")
    op.drop_index(op.f("ix_planning_runs_organization_id"), table_name="planning_runs")
    op.drop_table("planning_runs")
    op.drop_table("organizations")
    # ### end Alembic commands ###
